#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18408
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PDVTablet.Resource", IsApplication=true)]

namespace PDVTablet
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040007
			public const int activity_horizontal_margin = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int activity_vertical_margin = 2130968584;
			
			// aapt resource value: 0x7f040001
			public const int containe_height_cabecalho = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int container_CfgmarginBottom = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int container_CfgmarginLeft = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int container_CfgmarginRight = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int container_CfgmarginTop = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int container_imagem = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int container_logoBottom = 2130968576;
			
			// aapt resource value: 0x7f040009
			public const int container_mainmarginBottom = 2130968585;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bordaCabecalho = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bordaPretaTexto = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int brasystem = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int brasystemcortransp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int buttonStyle1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int buttonStyle2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int buttonStyle3 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int cabecalho = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icactionsettings = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int standardNewButton = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int styleEstruturaIndex = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070043
			public const int asdasdasda = 2131165251;
			
			// aapt resource value: 0x7f070031
			public const int bt_0 = 2131165233;
			
			// aapt resource value: 0x7f07002b
			public const int bt_1 = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int bt_2 = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int bt_3 = 2131165229;
			
			// aapt resource value: 0x7f070026
			public const int bt_4 = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int bt_5 = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int bt_6 = 2131165224;
			
			// aapt resource value: 0x7f070021
			public const int bt_7 = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int bt_8 = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int bt_9 = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int bt_divi = 2131165220;
			
			// aapt resource value: 0x7f070032
			public const int bt_igual = 2131165234;
			
			// aapt resource value: 0x7f070035
			public const int bt_limpar = 2131165237;
			
			// aapt resource value: 0x7f070029
			public const int bt_multi = 2131165225;
			
			// aapt resource value: 0x7f070030
			public const int bt_ponto = 2131165232;
			
			// aapt resource value: 0x7f070036
			public const int bt_sair = 2131165238;
			
			// aapt resource value: 0x7f070033
			public const int bt_soma = 2131165235;
			
			// aapt resource value: 0x7f07002e
			public const int bt_subt = 2131165230;
			
			// aapt resource value: 0x7f070042
			public const int btnCfg = 2131165250;
			
			// aapt resource value: 0x7f070044
			public const int btnLogin = 2131165252;
			
			// aapt resource value: 0x7f070011
			public const int btnSalvar = 2131165201;
			
			// aapt resource value: 0x7f07001b
			public const int btnTestar = 2131165211;
			
			// aapt resource value: 0x7f07001d
			public const int btnTestarTexto = 2131165213;
			
			// aapt resource value: 0x7f070012
			public const int btnVoltar = 2131165202;
			
			// aapt resource value: 0x7f07000e
			public const int button1 = 2131165198;
			
			// aapt resource value: 0x7f070019
			public const int checkCriticar = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int checkFiltro = 2131165210;
			
			// aapt resource value: 0x7f070018
			public const int checkMesas = 2131165208;
			
			// aapt resource value: 0x7f070004
			public const int codPoduto = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int desPoduto = 2131165191;
			
			// aapt resource value: 0x7f070040
			public const int editLogin = 2131165248;
			
			// aapt resource value: 0x7f070041
			public const int editSenha = 2131165249;
			
			// aapt resource value: 0x7f07003c
			public const int imageView1 = 2131165244;
			
			// aapt resource value: 0x7f07003e
			public const int imageView2 = 2131165246;
			
			// aapt resource value: 0x7f07000b
			public const int ladasdas = 2131165195;
			
			// aapt resource value: 0x7f070039
			public const int layoutLista = 2131165241;
			
			// aapt resource value: 0x7f070000
			public const int layoutMain = 2131165184;
			
			// aapt resource value: 0x7f070037
			public const int linearCenter = 2131165239;
			
			// aapt resource value: 0x7f07000c
			public const int linearLayout1 = 2131165196;
			
			// aapt resource value: 0x7f07003d
			public const int linearLayout11 = 2131165245;
			
			// aapt resource value: 0x7f070010
			public const int linearLayout12 = 2131165200;
			
			// aapt resource value: 0x7f07003a
			public const int linearLayout13 = 2131165242;
			
			// aapt resource value: 0x7f070017
			public const int linearLayout14 = 2131165207;
			
			// aapt resource value: 0x7f07003b
			public const int linearLayout15 = 2131165243;
			
			// aapt resource value: 0x7f070013
			public const int linearLayout16 = 2131165203;
			
			// aapt resource value: 0x7f07001c
			public const int linearLayout17 = 2131165212;
			
			// aapt resource value: 0x7f07003f
			public const int linearLayout18 = 2131165247;
			
			// aapt resource value: 0x7f070046
			public const int linearLayout19 = 2131165254;
			
			// aapt resource value: 0x7f07000f
			public const int linearLayout2 = 2131165199;
			
			// aapt resource value: 0x7f070002
			public const int linearLayout3 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int linearLayout4 = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int linearLayout5 = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int linearLayout6 = 2131165185;
			
			// aapt resource value: 0x7f070016
			public const int linearLayout7 = 2131165206;
			
			// aapt resource value: 0x7f070005
			public const int linearLayout8 = 2131165189;
			
			// aapt resource value: 0x7f07001e
			public const int linearLayoutCalc = 2131165214;
			
			// aapt resource value: 0x7f070038
			public const int linearView = 2131165240;
			
			// aapt resource value: 0x7f07000a
			public const int loader = 2131165194;
			
			// aapt resource value: 0x7f070008
			public const int qtdPoduto = 2131165192;
			
			// aapt resource value: 0x7f07001f
			public const int tableLayout1 = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int tableRow2 = 2131165216;
			
			// aapt resource value: 0x7f070025
			public const int tableRow3 = 2131165221;
			
			// aapt resource value: 0x7f07002a
			public const int tableRow4 = 2131165226;
			
			// aapt resource value: 0x7f07002f
			public const int tableRow5 = 2131165231;
			
			// aapt resource value: 0x7f070034
			public const int tableRow6 = 2131165236;
			
			// aapt resource value: 0x7f07000d
			public const int textView1 = 2131165197;
			
			// aapt resource value: 0x7f070014
			public const int txtIp = 2131165204;
			
			// aapt resource value: 0x7f070045
			public const int txtLogin = 2131165253;
			
			// aapt resource value: 0x7f070015
			public const int txtPorta = 2131165205;
			
			// aapt resource value: 0x7f070009
			public const int valPoduto = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int listaRowProduto = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int telaCfg = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int telaIndex = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int telaLogin = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int telaTeste = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int cinco = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int divisao = 2131034119;
			
			// aapt resource value: 0x7f05000d
			public const int dois = 2131034125;
			
			// aapt resource value: 0x7f050003
			public const int firstButton = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int firstTexto = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int firstTexto2 = 2131034114;
			
			// aapt resource value: 0x7f050012
			public const int igual = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int limpar = 2131034132;
			
			// aapt resource value: 0x7f05000b
			public const int multi = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int nove = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int oito = 2131034117;
			
			// aapt resource value: 0x7f050010
			public const int ponto = 2131034128;
			
			// aapt resource value: 0x7f050008
			public const int quatro = 2131034120;
			
			// aapt resource value: 0x7f050015
			public const int sair = 2131034133;
			
			// aapt resource value: 0x7f05000a
			public const int seis = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int sete = 2131034116;
			
			// aapt resource value: 0x7f050013
			public const int soma = 2131034131;
			
			// aapt resource value: 0x7f05000f
			public const int subt = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int tres = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int um = 2131034124;
			
			// aapt resource value: 0x7f050011
			public const int zero = 2131034129;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
