#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18408
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PDVTablet.Resource", IsApplication=true)]

namespace PDVTablet
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040001
			public const int containe_height_cabecalho = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int container_CfgmarginBottom = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int container_CfgmarginLeft = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int container_CfgmarginRight = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int container_CfgmarginTop = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int container_imagem = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int container_logoBottom = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int container_mainmarginBottom = 2130968583;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bordaPretaTexto = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int brasystem = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int brasystemcortransp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int buttonStyle1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int buttonStyle2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int buttonStyle3 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icactionsettings = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int standardNewButton = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060020
			public const int asdasdasda = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int btnCfg = 2131099679;
			
			// aapt resource value: 0x7f060021
			public const int btnLogin = 2131099681;
			
			// aapt resource value: 0x7f060006
			public const int btnSalvar = 2131099654;
			
			// aapt resource value: 0x7f060012
			public const int btnTestar = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int btnTestarTexto = 2131099669;
			
			// aapt resource value: 0x7f060007
			public const int btnVoltar = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int button1 = 2131099650;
			
			// aapt resource value: 0x7f060010
			public const int checkCriticar = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int checkFiltro = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int checkMesas = 2131099663;
			
			// aapt resource value: 0x7f06001d
			public const int editLogin = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int editSenha = 2131099678;
			
			// aapt resource value: 0x7f060019
			public const int imageView1 = 2131099673;
			
			// aapt resource value: 0x7f06001b
			public const int imageView2 = 2131099675;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f06001a
			public const int linearLayout11 = 2131099674;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout12 = 2131099653;
			
			// aapt resource value: 0x7f060017
			public const int linearLayout13 = 2131099671;
			
			// aapt resource value: 0x7f06000e
			public const int linearLayout14 = 2131099662;
			
			// aapt resource value: 0x7f060018
			public const int linearLayout15 = 2131099672;
			
			// aapt resource value: 0x7f060009
			public const int linearLayout16 = 2131099657;
			
			// aapt resource value: 0x7f060013
			public const int linearLayout17 = 2131099667;
			
			// aapt resource value: 0x7f06001c
			public const int linearLayout18 = 2131099676;
			
			// aapt resource value: 0x7f060023
			public const int linearLayout19 = 2131099683;
			
			// aapt resource value: 0x7f060003
			public const int linearLayout2 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int linearLayout3 = 2131099652;
			
			// aapt resource value: 0x7f060016
			public const int linearLayout4 = 2131099670;
			
			// aapt resource value: 0x7f060008
			public const int linearLayout5 = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int linearLayout7 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int linearLayout8 = 2131099661;
			
			// aapt resource value: 0x7f060014
			public const int loader = 2131099668;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			// aapt resource value: 0x7f06000a
			public const int txtIp = 2131099658;
			
			// aapt resource value: 0x7f060022
			public const int txtLogin = 2131099682;
			
			// aapt resource value: 0x7f06000b
			public const int txtPorta = 2131099659;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int telaCfg = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int TelaIndex = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int telaLogin = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int firstButton = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int firstTexto = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int firstTexto2 = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
